### ISSUE TITLE
ERROR: Line magic function `%mathplotlib` not found.

### ISSUE THREAD

**Issue by ualisher** [dataquestio/solutions#20]
I'm using jupiter provided by dataquest and I get an error 
"ERROR: Line magic function `%mathplotlib` not found". I searched online and the solutions are variants of installation of more recent versions of python. But since the jupiter resides on your server, I can't do that. Can you please suggest a solution? Thanks.

**Comment by jaypeedevlin** [comment]
Hi @ualisher,

The reason you are getting that error is because there is a typo in your code.

Instead of `%mathplotlib inline` you need `%matplotlib inline`, ie without the 'h'.

Also, the best place for support is to use the `?` icon at the top of the Dataquest platform - it could be really easy for a message here to get missed.

I hope this helps!
